# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7c35aeedefc8aa91ab697fc5ea99837b8b7f7dcd6973d67a3e167ce68dfbde2f5d982f5be8d02b58c34e3a4cbf365f23af0a8c2c760452bde1c7b197938f217

test:
  secret_key_base: 1ad1f076d41de9c8b3e5f49352a28d70ff5c8cd9ee8f7d9605dc46d298e9b3c7cb6e2da60cfcfb05524d5e30d3533e6cdc88a6c452abe1f825128a137f8cbfb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV['secret_key_base'] %>
  secret_token: <%= ENV['secret_key_base'] %>